genesis:
  chain_id: "spunky"
  app_state:
    staking:
      params:
        bond_denom: "uspunk"
accounts:
  - name: alice
    coins: ["100000000000uspunk"]
  - name: preet
    coins: ["100000000000uspunk"]
  - name: ali
    coins: ["100000000000uspunk"]
  - name: sonia
    coins: ["100000000000uspunk"]
  - name: berry
    coins: ["100000000000uspunk"]
  - name: tobias
    coins: ["100000000000uspunk"]
  - name: dennis
    coins: ["100000000000uspunk"]
validator:
  name: alice
  staked: "50000000000uspunk"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: alice
  coins: ["1000000000uspunk"]
